### PR TITLE
[JENKINS-47736] Jenkins-ClassFilter-Whitelisted

### PR DESCRIPTION
**Pull request by jglick**
See https://github.com/jenkinsci/jenkins/pull/3120#discussion_r154969882.

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
CI seems broken @aheritier.

**Comment by jglick** [comment]
Maybe this could be merged to `master` and then `cherry-pick`ed to a compatibility branch or something?

**Comment by oleg-nenashev** [comment]
@jglick Yes, makes sense. I will do that this week and make sure we get Maven Plugin released.

**Comment by oleg-nenashev** [comment]
@jglick could you please merge it with master so that we get CI passing?

**Pull request merged**
