### PR TITLE
Use Guice 4.0 instead of the beta release

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Follow-up to #6

CC @reviewbybees, @aheritier and @KostyaSha

### CODE REVIEW

**Comment by aheritier** [comment]
🐝 👍 cc @olamy FYI

**Comment by aheritier** [comment]
@KostyaSha it has the provided scope, I imagine we need it to compile. But we aren't exposing it. I'm not sure why.

**Comment by oleg-nenashev** [comment]
I prefer not to touch the build logic. The lib is pretty outdated, and it's hard to imagine the possible fallout in Maven Plugin and Artifactory. I have no interest in dealing with that fallout

**Comment by christ66** [comment]
🐝

**Comment by oleg-nenashev** [comment]
@reviewbybees done

**Comment by olamy** [comment]
+1

**Comment by oleg-nenashev** [comment]
🚢 🇮🇹 merging and releasing
thanks all!

**Comment by oleg-nenashev** [comment]
Heh, my local tests are failing after the integration with the master branch :(

```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 sec <<< FAILURE! - in hudson.maven.TestMavenEmbedderSimpleProjectWithParent
testSimpleProjectRead(hudson.maven.TestMavenEmbedderSimpleProjectWithParent)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.build()Lcom/google/common/cache/Cache;
	at com.google.inject.internal.WeakKeySet.<init>(WeakKeySet.java:55)
	at com.google.inject.internal.InheritingState.<init>(InheritingState.java:67)
	at com.google.inject.internal.InjectorShell$Builder.getState(InjectorShell.java:209)
	at com.google.inject.internal.InjectorShell$Builder.lock(InjectorShell.java:115)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at org.codehaus.plexus.DefaultPlexusContainer.addPlexusInjector(DefaultPlexusContainer.java:476)
	at org.codehaus.plexus.DefaultPlexusContainer.<init>(DefaultPlexusContainer.java:202)
	at org.codehaus.plexus.DefaultPlexusContainer.<init>(DefaultPlexusContainer.java:166)
	at hudson.maven.MavenEmbedderUtils.buildPlexusContainer(MavenEmbedderUtils.java:170)
	at hudson.maven.MavenEmbedderUtils.buildPlexusContainer(MavenEmbedderUtils.java:163)
	at hudson.maven.MavenEmbedder.<init>(MavenEmbedder.java:109)
	at hudson.maven.MavenEmbedder.<init>(MavenEmbedder.java:136)
	at hudson.maven.TestMavenEmbedderSimpleProjectWithParent.testSimpleProjectRead(TestMavenEmbedderSimpleProjectWithParent.java:55)
```

**Comment by oleg-nenashev** [comment]
Reverting this change due to the release build errors, see #8

**Pull request merged**
